apiVersion: v1
kind: Service
metadata:
  name: bitcoin-price-v1-service
spec:
  selector:
    app: bitcoin-price-v1-service
  type: ClusterIP
  ports:
    - port: 1957
      targetPort: 1957
      protocol: TCP